### ISSUE TITLE
Bug /bounties

### ISSUE THREAD

**Issue by Lqncelot** [Indyuce/bounty-hunters#106]
When I use the command / bounties, I get this error in the console:

[20:58:20 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bounties' in plugin BountyHunters v2.2.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[KitPvP.jar:git-NachoSpigot-"28047e7"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:147) ~[KitPvP.jar:git-NachoSpigot-"28047e7"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:704) ~[KitPvP.jar:git-NachoSpigot-"28047e7"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1359) ~[KitPvP.jar:git-NachoSpigot-"28047e7"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1171) ~[KitPvP.jar:git-NachoSpigot-"28047e7"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:55) ~[KitPvP.jar:git-NachoSpigot-"28047e7"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[KitPvP.jar:git-NachoSpigot-"28047e7"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:6) ~[KitPvP.jar:git-NachoSpigot-"28047e7"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_292]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [KitPvP.jar:git-NachoSpigot-"28047e7"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:784) [KitPvP.jar:git-NachoSpigot-"28047e7"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:398) [KitPvP.jar:git-NachoSpigot-"28047e7"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:723) [KitPvP.jar:git-NachoSpigot-"28047e7"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [KitPvP.jar:git-NachoSpigot-"28047e7"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.NullPointerException
        at java.lang.String.replace(String.java:2240) ~[?:1.8.0_292]
        at net.Indyuce.bountyhunters.gui.BountyList.getInventory(BountyList.java:60) ~[?:?]
        at net.Indyuce.bountyhunters.gui.PluginInventory.open(PluginInventory.java:16) ~[?:?]
        at net.Indyuce.bountyhunters.command.BountiesCommand.onCommand(BountiesCommand.java:39) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[KitPvP.jar:git-NachoSpigot-"28047e7"]
        ... 15 more
        
       
How I can fix?

**Comment by Indyuce** [comment]
Your BH build is outdated, update to latest
