### ISSUE TITLE
Compass dont work

### ISSUE THREAD

**Issue by Neeekss** [Indyuce/bounty-hunters#121]
server 1.18.2

[12:24:08 ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.PlayerInputEvent@3b2d3823 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[worldedit-bukkit-7.2.8.jar:?]
at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-bukkit-7.2.8.jar:?]
at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-bukkit-7.2.8.jar:?]
at com.sk89q.worldedit.WorldEdit.handleRightClick(WorldEdit.java:639) ~[worldedit-bukkit-7.2.8.jar:?]
at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:144) ~[worldedit-bukkit-7.2.8.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor21.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-341]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[paper-1.18.2.jar:git-Paper-341]
at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:507) ~[paper-1.18.2.jar:git-Paper-341]
at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[paper-1.18.2.jar:git-Paper-341]
at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[paper-1.18.2.jar:git-Paper-341]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1909) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:28) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-341]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-341]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-341]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-341]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-341]
at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1503) ~[paper-1.18.2.jar:git-Paper-341]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-341]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-341]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: com.sk89q.worldedit.bukkit.adapter.UnsupportedVersionEditException: Editing on unsupported versions is disabled.
at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:457) ~[worldedit-bukkit-7.2.8.jar:?]
at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.canPassThroughBlock(AbstractPlayerActor.java:432) ~[worldedit-bukkit-7.2.8.jar:?]
at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.advanceToWall(AbstractPlayerActor.java:444) ~[worldedit-bukkit-7.2.8.jar:?]
at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.passThroughForwardWall(AbstractPlayerActor.java:476) ~[worldedit-bukkit-7.2.8.jar:?]
at com.sk89q.worldedit.command.tool.NavigationWand.actPrimary(NavigationWand.java:63) ~[worldedit-bukkit-7.2.8.jar:?]
at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlayerInput(PlatformManager.java:425) ~[worldedit-bukkit-7.2.8.jar:?]
at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-bukkit-7.2.8.jar:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.2.8.jar:?]
... 30 more
Caused by: com.sk89q.worldedit.bukkit.adapter.UnsupportedVersionEditException: Editing on unsupported versions is disabled.
at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:457) ~[worldedit-bukkit-7.2.8.jar:?]
at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.canPassThroughBlock(AbstractPlayerActor.java:432) ~[worldedit-bukkit-7.2.8.jar:?]
at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.advanceToWall(AbstractPlayerActor.java:444) ~[worldedit-bukkit-7.2.8.jar:?]
at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.passThroughForwardWall(AbstractPlayerActor.java:476) ~[worldedit-bukkit-7.2.8.jar:?]
at com.sk89q.worldedit.command.tool.NavigationWand.actPrimary(NavigationWand.java:63) ~[worldedit-bukkit-7.2.8.jar:?]
at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlayerInput(PlatformManager.java:425) ~[worldedit-bukkit-7.2.8.jar:?]
at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-bukkit-7.2.8.jar:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.2.8.jar:?]
... 30 more

**Comment by Indyuce** [comment]
Lmk how to reproduce that issue, does it occur when WG and WE are uninstalled? If so what are the conditions in which I can reproduce that bug, does it have to be in a specific region?

**Comment by Neeekss** [comment]
If i remove WG and WE error is disappear and everything is working, I use compass in survival world where is 
regions:
    __global__:
        members: {}
        flags: {}
        owners: {}
        type: global
        priority: 0

**Comment by Indyuce** [comment]
The target compass works fine on my end (latest WE and WG on 1.19) altho I am getting the same issue which seems to be an issue with WorldEdit. It doesn't seem related to BH at all. I'm getting the same issue when right clicking a COMPASS, it doesn't have to be a BountyHunters compass

Make sure you have that config section in your config.yml and restart your server
```
# Player tracking lets player use a tracking compass to hunt
# down their bounty target. On the one hand, it gives an
# advantage to the hunters because they can find the player, but
# it also lets the target know how many players are tracking them.
player-tracking:
  enabled: true

  # Also displays particles around the
  # target when holding the compass.
  target-particles: true

  # Set to true if you want players able to target bounties
  # which they contributed in
  can-track-own-bounties: true

  # Price of the tracking compass.
  price: 1000

  # Cooldowns players need to wait before tracking a player.
  cooldown: 240
```
