### ISSUE TITLE
Can't remove bounties

### ISSUE THREAD

**Issue by ValhallaCraft** [Indyuce/bounty-hunters#126]
When people try to remove a bounty we get this error in console:

```- [Fri 00:28:18 ERROR Minecraft] Could not pass event InventoryClickEvent to BountyHunters v2.4.4
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "java.util.LinkedHashMap.get(Object)" is null
	at BountyHunters-2.4.4.jar//net.Indyuce.bountyhunters.api.Bounty.getContribution(Bounty.java:166)
	at BountyHunters-2.4.4.jar//net.Indyuce.bountyhunters.api.event.BountyExpireEvent.<init>(BountyExpireEvent.java:36)
	at BountyHunters-2.4.4.jar//net.Indyuce.bountyhunters.gui.BountyList.whenClicked(BountyList.java:228)
	at BountyHunters-2.4.4.jar//net.Indyuce.bountyhunters.gui.listener.GuiListener.a(GuiListener.java:16)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor632.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3047)
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58)
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23)
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358)
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
	at net.minecraft.util.threa
```

**Comment by Indyuce** [comment]
This will be fixed in the next devt build
