### ISSUE TITLE
Error occurred while enabling BountyHunters v2.4.4

### ISSUE THREAD

**Issue by KingdomsMineMC** [Indyuce/bounty-hunters#130]
```
[13:24:08] [Server thread/ERROR]: Error occurred while enabling BountyHunters v2.4.4 (Is it up to date?)
java.lang.NoClassDefFoundError: de/simonsator/partyandfriends/spigot/api/pafplayers/PAFPlayerManager
	at net.Indyuce.bountyhunters.compat.interaction.external.PartyAndFriendsSupport.<init>(PartyAndFriendsSupport.java:9) ~[BountyHunters.jar:?]
	at net.Indyuce.bountyhunters.BountyHunters.onEnable(BountyHunters.java:238) ~[BountyHunters.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-138]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-138]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-138]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: de.simonsator.partyandfriends.spigot.api.pafplayers.PAFPlayerManager
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 13 more
[13:24:08] [Server thread/INFO]: [BountyHunters] Disabling BountyHunters v2.4.4
```

**Comment by Indyuce** [comment]
Make sure you have your PAF up to date. We're building BH against the latest version of the PAF API build
