### ISSUE TITLE
some help ?

### ISSUE THREAD

**Issue by AlexandruSAN2** [Indyuce/bounty-hunters#16]
[09:49:42] [Server thread/INFO]: [BountyHunters] Enabling BountyHunters v2.2.6
[09:49:42] [Server thread/INFO]: [BountyHunters] Detected Server Version: v1_12_R1
[09:49:42] [Server thread/ERROR]: [BountyHunters] Your server version is not handled with NMS.
[09:49:42] [Server thread/INFO]: [BountyHunters] Hooked onto PlaceholderAPI
[09:49:42] [Server thread/ERROR]: Error occurred while enabling BountyHunters v2.2.6 (Is it up to date?)
java.lang.NoSuchFieldError: PLAYER_HEAD
	at net.Indyuce.bountyhunters.api.CustomItem.<clinit>(CustomItem.java:23) ~[?:?]
	at net.Indyuce.bountyhunters.BountyHunters.onEnable(BountyHunters.java:154) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Paper-1618]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[spigot.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[spigot.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[spigot.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[spigot.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[09:49:42] [Server thread/INFO]: [BountyHunters] Disabling BountyHunters v2.2.6

**Comment by Indyuce** [comment]
2.2.1 is the latest version available for 1.12
