### ISSUE TITLE
Error Enabling Bounty-Hunters

### ISSUE THREAD

**Issue by FunkyNico** [Indyuce/bounty-hunters#20]
When i startup the server i see this error:

```
[16:43:09 INFO]: [BountyHunters] Enabling BountyHunters v2.2.6
[16:43:09 INFO]: [BountyHunters] Detected Server Version: v1_14_R1
[16:43:09 ERROR]: Error occurred while enabling BountyHunters v2.2.6 (Is it up to date?)
java.lang.NullPointerException: null
        at net.Indyuce.bountyhunters.manager.LevelManager.reload(LevelManager.java:60) ~[?:?]
        at net.Indyuce.bountyhunters.manager.LevelManager.<init>(LevelManager.java:28) ~[?:?]
        at net.Indyuce.bountyhunters.BountyHunters.onEnable(BountyHunters.java:141) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-237]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-237]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-237]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-237]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[16:43:09 INFO]: [BountyHunters] Disabling BountyHunters v2.2.6
```

**Server:** Paper version git-Paper-237 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
**Plugins:**  BountyHunters, Essentials, EssentialsChat, EssentialsSpawn, LuckPerms, ProtocolLib, Vault
**Plugin Version:** BountyHunters v2.2.6

**Comment by Indyuce** [comment]
Have you tried resetting your plugin folder? This issue usually happens after a 2.2.x plugin update.

**Comment by FunkyNico** [comment]
> Have you tried resetting your plugin folder? This issue usually happens after a 2.2.x plugin update.

Yeah, if you delete the folder of the plugin and then regenerate it on the startup it works fine.
It's seems that of some way i put in the plugins folder an older version and then i replace it with a newer and that produces the issue, the thing is that i never used an older version before lol.
