### ISSUE TITLE
Make offline player lookup async

### ISSUE THREAD

**Issue by NotMyFault** [Indyuce/bounty-hunters#22]
I just noticed the following recommendation on my console:

```
[01:44:42 ERROR]: Could not pass event InventoryClickEvent to BountyHunters v2.3.5
java.lang.RuntimeException: The operation to load user data for '7e4743f8-ea95-40be-b876-3d9f88090d29' was cancelled by LuckPerms. This is NOT a bug.
The lookup request was made on the main server thread. It is not safe to execute a request to
load data for offline players from the database in this context.
If you are a plugin author, please consider making your request asynchronously.
Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true
in the LP config, but should consider the consequences (lag) before doing so.
at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.lookupUser(LuckPermsVaultPermission.java:166) ~[?:?]
at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.userHasPermission(LuckPermsVaultPermission.java:192) ~[?:?]
at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.playerHas(AbstractVaultPermission.java:154) ~[?:?]
at net.Indyuce.bountyhunters.gui.BountyList.whenClicked(BountyList.java:182) ~[?:?]
at net.Indyuce.bountyhunters.gui.listener.GuiListener.a(GuiListener.java:17) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor441.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-62]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-62]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-62]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2328) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:1037) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1030) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1014) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:937) ~[patched_1.15.1.jar:git-Paper-62]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

I know, you can simply disable it. But since Bounty Hunters was the first plugin I actually noticed it on, I thought you might want to change the method.
Tested on BountyHunters Premium 2.3.5 and LuckPerms 5.0.56

**Comment by Indyuce** [comment]
Should be fixed in the next build
