### ISSUE TITLE
Bug/error

### ISSUE THREAD

**Issue by UrTinySaucisse** [Indyuce/bounty-hunters#25]
Bounty hunters isn't working for me, maybe the wrong version? I'm on spigot 1.12.2 (most stable)

https://hastebin.com/ofiweriqoy.css

--> If the hastebin must me invalid:

> [17:10:42 INFO]: [BountyHunters] Enabling BountyHunters v2.2.6
> [17:10:42 INFO]: [BountyHunters] Detected Server Version: v1_12_R1
> [17:10:42 ERROR]: [BountyHunters] Your server version is not handled with NMS.
> [17:10:42 INFO]: [BountyHunters] Hooked onto PlaceholderAPI
> [17:10:42 ERROR]: Error occurred while enabling BountyHunters v2.2.6 (Is it up to date?)
java.lang.NoSuchFieldError: PLAYER_HEAD
at net.Indyuce.bountyhunters.api.CustomItem.<clinit>(CustomItem.java:23) ~[?:?]
at net.Indyuce.bountyhunters.BountyHunters.onEnable(BountyHunters.java:154) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by Indyuce** [comment]
You need 2.2.1 in order to run BountyHunters on legacy spigot builds (1.8-1.12). 2.2.6 is only for 1.13+. However if you are running BountyHunters Premium, there's only one build for 1.9 up to 1.15
