### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by Tradie18** [Indyuce/bounty-hunters#26]
I have changed all my messages in messages.yaml

Since then, /bounty  spits out the following error.

[ERROR] null

org.bukkit.command.CommandException: Unhandled exception executing command 'bounty' in plugin BountyHunters v2.2.6

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[?:git-Spigot-cbd1a1b-009d8af]

at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[?:git-Spigot-cbd1a1b-009d8af]

at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at net.minecraft.server.v1_14_R1.PlayerConnectionUtils$$Lambda$4622.00000000B408A6A0.run(Unknown Source) ~[?:?]

at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:885) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

Caused by: java.lang.IllegalArgumentException: Cannot translate null text

at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:354) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

at net.Indyuce.bountyhunters.api.Message.getMessage(Message.java:79) ~[?:?]

at net.Indyuce.bountyhunters.api.Message.formatRaw(Message.java:91) ~[?:?]

at net.Indyuce.bountyhunters.api.Message.format(Message.java:106) ~[?:?]

at net.Indyuce.bountyhunters.api.event.BountyChangeEvent.sendAllert(BountyChangeEvent.java:34) ~[?:?]

at net.Indyuce.bountyhunters.command.AddBountyCommand.onCommand(AddBountyCommand.java:128) ~[?:?]

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]

... 18 more

**Comment by Indyuce** [comment]
Probably a config issue. Try reseting your languages config file and see if the issue persists
