### ISSUE TITLE
Error when using /bounties or /hunters

### ISSUE THREAD

**Issue by ViibeMC** [Indyuce/bounty-hunters#4]
Here is the error when running the command: 

> [19:12:52 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bounties' in plugin BountyHunters v2.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-d3e0b6f]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-d3e0b6f]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException

**Comment by Indyuce** [comment]
Have you updated to >2.1 recently? You might need to reset your data.yml while your server is off after updating to a recent version. Also make sure there are no other error logs, especially when the server starts up, this issue might be due to a compatibility bug with WorldGuard.

**Comment by ViibeMC** [comment]
Unfortunately because of the setup i have on my server, I'm running BountyHunterLegcay.jar

**Comment by Indyuce** [comment]
Update to the latest version, backup & delete your data.yml and double check for startup error logs.

**Comment by Indyuce** [comment]
I tried running BH on 1.8.8 with Vault and EssentialsX for economy, /bounties seems fine.
