### ISSUE TITLE
Error occurred while enabling BountyHunters v2.3.9

### ISSUE THREAD

**Issue by efinst0rm** [Indyuce/bounty-hunters#48]
Hey,
Seem to have this issue with the lastest version running on 1.16.1
`[18:51:07 ERROR]: Error occurred while enabling BountyHunters v2.3.9 (Is it up to date?)
java.lang.NullPointerException: null
at net.Indyuce.bountyhunters.api.language.Message.update(Message.java:114) ~[?:?]
at net.Indyuce.bountyhunters.BountyHunters.onEnable(BountyHunters.java:230) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-86]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-86]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-86]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-86]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-86]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[18:51:07 INFO]: [BountyHunters] Disabling BountyHunters v2.3.9`

Thank You.

**Comment by Indyuce** [comment]
Try resetting your language files, especially messages.yml

**Comment by efinst0rm** [comment]
Hi Indyuce,

Thanks resetting my messages.yml has fixed my problem.
