### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ShadOhh** [Indyuce/bounty-hunters#55]
So i tried /bounties and this is the error I got in the console.

>.... [18:54:04 INFO]: Mineralized issued server command: /bounties
>.... [18:54:04 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bounties' in plugin BountyHunters v2.3.9
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-380]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-380]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-380]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1869) ~[patched_1.15.2.jar:git-Paper-380]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1677) ~[patched_1.15.2.jar:git-Paper-380]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-380]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-380]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-380]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-380]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-380]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-380]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-380]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105) ~[patched_1.15.2.jar:git-Paper-380]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098) ~[patched_1.15.2.jar:git-Paper-380]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-380]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1232) ~[patched_1.15.2.jar:git-Paper-380]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-380]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
at net.Indyuce.bountyhunters.api.CustomItem$Builder.applyPlaceholders(CustomItem.java:99) ~[?:?]
at net.Indyuce.bountyhunters.gui.BountyList.getInventory(BountyList.java:60) ~[?:?]
at net.Indyuce.bountyhunters.gui.PluginInventory.open(PluginInventory.java:20) ~[?:?]
at net.Indyuce.bountyhunters.command.BountiesCommand.onCommand(BountiesCommand.java:42) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-380]

I've reinstalled both the config files and the plugin itself and it still ended up the same. This is the latest version btw

**Comment by Indyuce** [comment]
Can you pastebin your latest server logs? Not sure what's happening there if you have already tried resetting your language folder

**Comment by ShadOhh** [comment]
Yeah this is the latest i've reinstalled the whole file itself.

**Comment by Indyuce** [comment]
I have tried running BH on a fresh paper 1.15 server setup and /bounties worked fine, can you try this on your end?

**Comment by ShadOhh** [comment]
ok let me see
1 sec

**Comment by ShadOhh** [comment]
is there something that its noncompatible with?

**Comment by Indyuce** [comment]
I'm not sure if it's an actual plugin bug or an incompatibility issue, again I'd like to check the server logs to make sure there are no loading issues

**Comment by ShadOhh** [comment]
Hi sorry for not responding for nearly a month been busy. So anyways I currently don't have enough resources to start a fresh server but I do think I know the reason why its bugging out. Im using this plugin called royaleconomy and it has its own money system different than essentials. but it uses vault. any ideas?

**Comment by Indyuce** [comment]
No idea. Please try running BH on a fresh server setup and see if the issue persists. If it doesn't you should try and remove your plugins one by one to check which one is interfering with BH.
Please also link your latest server logs including the error log when performing /bounties
