### ISSUE TITLE
[2.3.11] MySQL not syncing data?

### ISSUE THREAD

**Issue by ofseaandstars** [Indyuce/bounty-hunters#60]
**Please include a `latest.log` uploaded to [pastebin.com](https://pastebin.com) here:**
https://pastebin.com/M87BQN7T

**Describe the bug**
Using MySQL to share data across two servers, but even though the database details are correct, the data is not updating (such as number of bounties for players etc). Additionally, bounties set on Server 1 do not seem to be visible on Server 2. 

**To Reproduce**
1. Set up two servers with MySQL enabled and same details.
2. Set bounty on Server 1 on a player.
3. Go to Server 2 and run `/bounties`.
4. There will be no bounties listed for the relevant player.
5. Claim the bounty on server 1.
6. MySQL database will not show the updated claimed bounty count for the player who completed the bounty.

**Expected behavior**
Bounties should be synced across each server, and should be displayed in the MySQL `playerData` table.

**Screenshots**

*View of MySQL database table*
![image](https://user-images.githubusercontent.com/5949532/90984667-601e8e80-e56e-11ea-8515-d0d898b6172c.png)

**Server info:**
 - Tuinity 1.16.1
 - 2.3.11

**Additional information**
No errors in the console.
`?autoReconnect=true` is also enabled in the `extra-args:` section.

Another note, but as a general 'best practice' point, it would be better if the relevant MySQL tables were called `bountyhunters_bounties` and `bountyhunters_playerData` instead of just `bounties` or `playerData` as these are ambiguous and could potentially interfere with other plugins (though unlikely).

**Comment by ofseaandstars** [comment]
Correction - the player data *is* updating, but active bounties are still not visible on the other server, and leaderboard is also not displaying.

When running the `/hunters` command on the server where the bounty was claimed, this error shows up (note: this was after a server restart):
```
[19:37:00 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'hunters' in plugin BountyHunters v2.3.11
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1923) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1734) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1192) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1185) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1161) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.NullPointerException
        at net.Indyuce.bountyhunters.gui.Leaderboard.applyPlaceholders(Leaderboard.java:72) ~[?:?]
        at net.Indyuce.bountyhunters.gui.Leaderboard.getInventory(Leaderboard.java:46) ~[?:?]
        at net.Indyuce.bountyhunters.gui.PluginInventory.open(PluginInventory.java:20) ~[?:?]
        at net.Indyuce.bountyhunters.command.HuntersCommand.onCommand(HuntersCommand.java:25) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        ... 18 more
[19:37:00 WARN]: [BountyHunters] Plugin BountyHunters v2.3.11 generated an exception while executing task 14507
java.lang.NullPointerException: null
        at net.Indyuce.bountyhunters.gui.Leaderboard.lambda$0(Leaderboard.java:42) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.1.jar:git-Tuinity-"adf6055"]  
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]```

**Comment by Indyuce** [comment]
The current implementation of MySQL does not allow for data syncronization between servers, it's only an alternative for YAML which is pretty limited, unfortunately my MySQL skills are limited too

**Comment by S0ly** [comment]
is it still not syncronized between servers ??? because i really need it

**Comment by S0ly** [comment]
@Indyuce please make it for server network i really need this if its not i can't use it
