### ISSUE TITLE
hunters command exception

### ISSUE THREAD

**Issue by myfbone** [Indyuce/bounty-hunters#7]
```
[14:08:24 INFO]: KevinMitnik issued server command: /hunters
[14:08:24 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'hunters' in plugin BountyHunters v2.2.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.3.jar:git-Paper-122]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.3.jar:git-Paper-122]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:738) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1831) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1639) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:978) ~[patched_1.14.3.jar:git-Paper-122]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-122]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at net.Indyuce.bountyhunters.gui.Leaderboard.getInventory(Leaderboard.java:44) ~[?:?]
        at net.Indyuce.bountyhunters.gui.PluginInventory.open(PluginInventory.java:20) ~[?:?]
        at net.Indyuce.bountyhunters.command.HuntersCommand.onCommand(HuntersCommand.java:25) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.3.jar:git-Paper-122]
        ... 17 more
```
minecraft version: 1.14.3
paper version: 122
BountyHunters version: 2.2.4

Summary:
Yesterday this command worked, but today it's throwing and exception

**Comment by kassadGLA** [comment]
@Indyuce I think people download the build from SpigotMC which is not the latest version. I have no problems with the latest version that you sent me.

**Comment by myfbone** [comment]
Where I can get the latest version?

**Comment by Indyuce** [comment]
I tried running on a 1.14.3 spigot server the latest available version of BountyHunters, had no problem running /hunters. This issue needs some more investigation - double check your console for other error logs, if you're unsure send the whole file.
Make sure your plugin data is not in any way corrupted.

**Comment by myfbone** [comment]
My data file and log:
https://send.firefox.com/download/73eb9587cfe5a96c/#WtNKZxl8WNWhppAU44ELXA

**Comment by Indyuce** [comment]
Have you tried resetting your plugin data while the server is off?

**Comment by Indyuce** [comment]
It looks like the plugin is trying to grab info from an offline player which can't be retrieved, have you tried backing up and temporarily deleting your player data, especially cache/leaderboard.yml?

**Comment by myfbone** [comment]
No I have not

**Comment by myfbone** [comment]
Should I?

**Comment by Indyuce** [comment]
Yes

**Comment by Indyuce** [comment]
Closed till more information is provided
