### ISSUE TITLE
None of the commands work for me

### ISSUE THREAD

**Issue by ZaidSu** [Indyuce/bounty-hunters#82]
Console Error:
 [16:06:11 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bounties' in plugin BountyHunters v2.3.14
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2258) ~[?:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2073) ~[?:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2026) ~[?:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1321) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1314) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1290) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at net.Indyuce.bountyhunters.api.CustomItem$Builder.applyPlaceholders(CustomItem.java:102) ~[?:?]
        at net.Indyuce.bountyhunters.gui.BountyList.getInventory(BountyList.java:63) ~[?:?]
        at net.Indyuce.bountyhunters.gui.PluginInventory.open(PluginInventory.java:20) ~[?:?]
        at net.Indyuce.bountyhunters.command.BountiesCommand.onCommand(BountiesCommand.java:42) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        I don't know why none of the commands work I tried deleting the plugin and then downloading it again and my server version is 1.16.5.

**Comment by Indyuce** [comment]
This issue is being worked on, it's probably due to some bounty placed on a player that logged off a while ago and never logged back on the server, since spigot can't recognize that player the bounty is making the server crash everytime you try to open the bounties menu

**Comment by ZaidSu** [comment]
Ohhh okay should I try deleting like the player data folder and restart the server?

**Comment by Indyuce** [comment]
Can you give 2.3.15 a try ?

**Comment by ZaidSu** [comment]
Well it works now thank you very much sorry for the late reply as well! But I appreciate it very much!
 Thank you

**Comment by ZaidSu** [comment]
actually I get this error now after I updated the version 
[05:29:23 ERROR]: Could not load 'plugins/BountyHunters.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: net/Indyuce/bountyhunters/BountyHunters has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:279) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.UnsupportedClassVersionError: net/Indyuce/bountyhunters/BountyHunters has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:201) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.buk

**Comment by Indyuce** [comment]
Same error as #84, you need to update to java 16

**Comment by Indyuce** [comment]
Closed till more info is provided
