### ISSUE TITLE
Random error in console

### ISSUE THREAD

**Issue by myfbone** [Indyuce/bounty-hunters#9]
minecraft version: 1.14.3
paper version: 124
BountyHunters version: 2.2.4
```
[22:47:32 ERROR]: Could not pass event PlayerDeathEvent to BountyHunters v2.2.4
java.lang.NullPointerException: null
        at net.Indyuce.bountyhunters.listener.BountyClaim.a(BountyClaim.java:166) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor410.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.3.jar:git-Paper-124]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-124]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-124]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.3.jar:git-Paper-124]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:766) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.EntityPlayer.die(EntityPlayer.java:580) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1198) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.EntityHuman.damageEntity(EntityHuman.java:770) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.EntityPlayer.damageEntity(EntityPlayer.java:751) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.EntityHuman.attack(EntityHuman.java:1031) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.EntityPlayer.attack(EntityPlayer.java:1676) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2062) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:978) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-124]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Indyuce** [comment]
- Elaborate, "random error" doesn't help me much.
- 2.2.4 is not the latest version, please send error logs using the latest plugin version.

**Comment by myfbone** [comment]
How can I give you more if I just look in console and see this error. Without any commands before or smth else

**Comment by Indyuce** [comment]
Please send logs using the latest plugin version, I can't fix your issue if you're not using the latest plugin version.

**Comment by Indyuce** [comment]
Closed till more info is provided
